title: "Hyeonhan's Blog"
description: "Minimal Mistakes를 이용한 블로그"
url: "https://hyeonhan.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"   # ✅ GitHub Pages 지원되는 방식

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache

# 기본 글 설정
author:
  name   : "Taks"
  avatar : "/assets/images/avatar_resized_200x200.png"
  bio    : "개발과 사진을 좋아합니다."

markdown: kramdown
