title: "Taks' Blog"
description: "이건 내 깃허브 블로그야"
url: "https://taks.github.io"
baseurl: ""
theme: "minimal-mistakes-jekyll"

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# 기본 글 설정
author:
  name   : "Taks"
  avatar : "/assets/images/avatar.png"
  bio    : "개발과 사진을 좋아합니다."

markdown: kramdown
